/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Todo_Manager;



import lombok.extern.java.Log;

import java.io.IOException;
import java.util.UUID;
import java.nio.file.Paths;


@Log
public class App {
    public String getGreeting() {
        log.info("string log test");
        return "Hello World!";

    }

    public static void main(String[] args) throws IOException {
        new Sort(true, true, true, true);//TODO remove once sort works
        Manager.loadUsers();
        UI.main(args);
    }
}

